### ISSUE TITLE
Bump the version number?

### ISSUE THREAD

**Issue by johnsturgeon** [xcodinas/apex-legends#17]
Hey @xcodinas    I noticed you bumped the version number the last time, and tbh, I'm not really sure how that works (pip submissions, etc...) but should we bump it for the 'sessions' data?

**Comment by xcodinas** [comment]
Hello, I will increase the version number and upload the pip package after I got the tests working

Edit: Got it working so https://github.com/xcodinas/apex-legends/commit/069c262baef09080d58fad02f5888700ec52e370

**Comment by johnsturgeon** [comment]
Thanks also for writing 'proper' unit tests!
